### ISSUE TITLE
i can not install code server!

### ISSUE THREAD

**Issue by sebasop320** [andreivisan/Raspberry-Pi-4-Code-Server#2]
Hello i'm having a isue instaling code server.

This is my error
`pi@raspberrypi:~ $ curl -fsSL https://code-server.dev/install.sh | sh

Raspbian GNU/Linux 10 (buster)
No standalone releases for armv7l.
Falling back to installation from npm.
Installing latest from npm.

Please install npm or yarn to install code-server!
You will need at least node v12 and a few C dependencies.
See the docs https://coder.com/docs/code-server/latest/install#yarn-npm`

i have npm and node also yarn installed

can someone help me!?

**Comment by JaroslavRobert** [comment]
Hi, try:
1. `sudo su`
2. `sudo npm install -g yarn`
3. `sudo curl -fsSL https://code-server.dev/install.sh | sh`

**Comment by sebasop320** [comment]
Ok I’m goin to try it

Thanks

**Comment by sebasop320** [comment]
Thanksss!!!

you are my heroe :D
